[package]
name = "aoc2023"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helper = { workspace = true }
z3 = {version = "0.12.1", features = ["static-link-z3"]}
