[package]
name = "aoc2015"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helper = { workspace = true }
linkme = { workspace = true }
log = { workspace = true }
md-5 = { workspace = true }
serde_json = { workspace = true }
