name: Rust

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ["2021", "2022"]
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check Rustfmt
      run: cargo fmt --manifest-path year${{matrix.year}}/Cargo.toml -- --check
    - name: Build
      run: cargo build --manifest-path year${{matrix.year}}/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path year${{matrix.year}}/Cargo.toml --verbose
