name: Rust

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy: 
        matrix:
            year: [2015, 2021, 2022, 2023, 2024]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.CHECKOUT_PAT }}
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Check Rustfmt
      run: cargo fmt --manifest-path crates/year${{matrix.year}}/Cargo.toml -- --check
    - name: Build
      run: cargo build --manifest-path crates/year${{matrix.year}}/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path crates/year${{matrix.year}}/Cargo.toml --verbose
