name: Rust

on:
  workflow_call:
    secrets:
      CHECKOUT_PAT:
        required: true
    inputs:
      year:
        required: true
        type: number
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.CHECKOUT_PAT }}
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Check Rustfmt
      run: cargo fmt --manifest-path crates/year${{inputs.year}}/Cargo.toml -- --check
    - name: Build
      run: cargo build --manifest-path crates/year${{inputs.year}}/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path crates/year${{inputs.year}}/Cargo.toml --verbose
