name: Rust

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build2021:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Rustfmt
      run: cd year2021 && cargo fmt -- --check
    - name: Build
      run: cd year2021 && cargo build --verbose
    - name: Run tests
      run: cd year2021 && cargo test --verbose

  build2022:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Rustfmt
      run: cd year2022 && cargo fmt -- --check
    - name: Build
      run: cd year2022 && cargo build --verbose
    - name: Run tests
      run: cd year2022 && cargo test --verbose
