name: AoC 2023

on:
  push:
    branches: [ master, main ]
    paths-ignore:
        - "year*/"
        - "!year2023/**"
  pull_request:
    branches: [ master, main ]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    with:
      year: 2023
