name: AoC 2015

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - "crates/year*/**"
      - "inputs/*/year*/**"
      - "inputs/personal"
      - "!crates/year2015/**"
      - "!inputs/*/year2015/**"
  pull_request:
    branches: [ master, main ]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    secrets: inherit
    with:
      year: 2015
