name: AoC 2022

on:
  push:
    branches: [ master, main ]
    paths-ignore:
        - "year*"
        - "!year2021"
  pull_request:
    branches: [ master, main ]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    with:
      year: 2022
