name: AoC 2021

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - "crates/year*/**"
      - "inputs/*/year*/**"
      - "!crates/year2021/**"
      - "!inputs/*/year2021/**"
  pull_request:
    branches: [ master, main ]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    secrets: inherit
    with:
      year: 2021
