name: AoC 2022

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - "crates/year*/**"
      - "inputs/*/year*/**"
      - "!crates/year2022/**"
      - "!inputs/*/year2022/**"
  pull_request:
    branches: [ master, main ]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    secrets: inherit
    with:
      year: 2022
